@WebUI_HostAddress = https://localhost:7257

### User Authenticate
POST {{WebUI_HostAddress}}/users/authenticate
Accept: application/json
Content-Type: application/json

{
  "name": "admin",
  "password": "admin"
}

### GET Document by id
GET {{WebUI_HostAddress}}/documents/1
Accept: application/json
Content-Type: application/json

{
  "name": "admin",
  "password": "admin"
}

### POST upload document
POST {{WebUI_HostAddress}}/documents
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="userId"

1

--boundary
Content-Disposition: form-data; name="file"; filename="haben или sein.jpg"
Content-Type: image/jpeg

< ./haben или sein.jpg
--boundary

### Create shared link
POST {{WebUI_HostAddress}}/documents/9/share
Accept: application/json
Content-Type: application/json

{
  "DurationInSeconds": 240
}
